---
name: LAMP Deployment

on:
    workflow_dispatch:
    push:
      branches:
        - main
    pull_request:

jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest

    steps:
    - name: Checkout sources
      uses: actions/checkout@v2
    - name: Linting
      uses: ansible-community/ansible-lint-action@main
      with:
        path: "ansible/"
    - name: Publish Playbook Artifact
      uses: actions/upload-artifact@v2
      with:
        name: playbooks
        path: ansible
  
  deploy_to_test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: linting
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/download-artifact@v2
        with:
          name: playbooks
          path: ansible
      
      - uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: playbook.yml
          directory: ansible
          options: |
            --inventory inventory-test.yml
            --extra-vars "test_ssh_password=${{ Secrets.TEST_SSH_PASSWORD }}"
...
